### ISSUE TITLE
Search doesn't find "horrible" in "Dr. Horrible's Sing-Along Blog"

### ISSUE THREAD

**Issue by bpk667** [moz667/homodaba#11]
Searching "along" or "sing-along" returns expected result, but "horrible" or "Horrible" don't work.
"Horrible's" and "horrible's" work too.

**Comment by moz667** [comment]
Listo a medias... he apañado para que te encuentre parciales de texto pero Elastic Search tiene muchas mas posibilidades pero yo no tengo npi de como funciona... Le di soporte en la app porque soy un flipado pero si quisieramos seguir usandolo deberiamos leernos como funciona:

Info para que miremos: 
    https://www.elastic.co/guide/en/elasticsearch/reference/7.x/index.html
    https://elasticsearch-dsl.readthedocs.io/
    https://django-elasticsearch-dsl-drf.readthedocs.io/

Commit con los cambios: https://github.com/moz667/homodaba/commit/d021b8dd73bd5b6b8e40079a07a1c3360c45968e
