### ISSUE TITLE
Search doesn't find "decálogo" in "El decálogo"

### ISSUE THREAD

**Issue by bpk667** [moz667/homodaba#13]
Also tried "decálogo. " and "decálogo." and no match.
"Dekalog" works though.

![image](https://user-images.githubusercontent.com/16985558/127747674-b264eebc-f82d-49e2-bebb-b0562ca973df.png)

**Comment by moz667** [comment]
Arreglado: https://github.com/moz667/homodaba/commit/dd4d75b44c5c71c0d87d3d61198d652a78aaeaa2
